### PR TITLE
Use layout for accessing /usr/

### PR DESCRIPTION
**Pull request by sudeephb**
Made some changes based on suggestions in: https://forum.snapcraft.io/t/allow-use-of-system-files-interface-for-prometheus-apt-exporter/32731/3

### CODE REVIEW

**Review by mkalcok — CHANGES_REQUESTED** [review]
My only suggestion would be to rename the executable...for example to `apt-exporter-wrapper.sh`. What do you think?

Also, if you are changing name of the plug, don't forget to update it in charm as well.

**Review by mkalcok — APPROVED** [review]
LGTM. +1

**Review by jneo8 — APPROVED** [review]
LGTM +1

**Review by mkalcok — APPROVED** [review]
LGTM. +1

**Pull request merged**
